Repository dotnet/ef6, pull requests merged in 2019-09, with the labels that each got.

#1251 Revert "Query compilation performance (#430)"
  src/EntityFramework/Core/Query/InternalTrees/VarMap.cs
  src/EntityFramework/Core/Query/InternalTrees/VarVec.cs
  src/EntityFramework/Core/Query/PlanCompiler/ColumnMapTranslator.cs
  src/EntityFramework/Core/Query/PlanCompiler/ITreeGenerator.cs
  src/EntityFramework/Core/Query/PlanCompiler/NestPullup.cs
  src/EntityFramework/Core/Query/PlanCompiler/VarRemapper.cs
  test/EntityFramework/UnitTests/Core/Query/InternalTrees/VarVecTests.cs
Labels: ask-mode

#1276 Update to 5.0 SDK
  Directory.Build.targets
  global.json
Labels: area-infrastructure

#1293 Update branding to 3.0.1
  eng/Versions.props
Labels: area-platform

#1317 Update branding to 6.4.0-preview2
  eng/Versions.props
Labels: area-platform
